nilton pr
Guardians-DSC/iarl-who pull request #12
Opened 2019-04-04 15:09 UTC by niltonmng

Estou motivado em fazer parte do IARL, pois acredito que pode ser um crescimento profissional no sentido de aprender e me aprimorar cada vez mais, para ganhar espaço no mercado de trabalho.
Outro tópico interessante seria o fato das tecnologias utilizadas, me interesso por trabalhar com NodeJs no backend ( já trabalhei com nodejs em duas disciplinas, ES e P1 ) e React no Front, visto sua popularidade no mercado.

2019-04-06 15:58 UTC, dfquaresma requested changes
Agradecemos o interesse em fazer parte do time! Poderia conferir as modificações que pedi abaixo? Valeu!

2019-04-06 15:58 UTC, dfquaresma commented on who/niltonginani.js
> +
```suggestion
```

2019-04-06 15:58 UTC, dfquaresma commented on who/niltonginani.js
> +
Poderia remover essa linha para manter o mesmo padrão dos demais arquivos?

2019-04-06 16:08 UTC, niltonmng commented on who/niltonginani.js
> +
Apliquei a sugestão!

2019-04-07 14:21 UTC, dfquaresma approved these changes

2019-04-24 01:20 UTC, merged