Raiany Rufino
Guardians-DSC/iarl-who pull request #14
Opened 2019-04-05 00:39 UTC by raianyrufino

Gostaria de adquirir conhecimento nas áreas em que a célula IARL atua por meio da experiência, e assim, obter crescimento individual, acadêmico e profissional. Além de que são áreas que tenho interesse em experimentar já que estão ganhando poder cada dia mais.

2019-04-06 16:05 UTC, dfquaresma requested changes
Obrigado @raianyrufino pelo interesse em fazer parte do time! Poderia conferir as mudanças que sugeri? Obrigado!

2019-04-06 16:05 UTC, dfquaresma commented on who/raianyrufino.js
> +});
```suggestion
});

```

2019-04-06 16:05 UTC, dfquaresma commented on who/raianyrufino.js
> +});
Poderia adicionar uma linha após o ";" para manter o padrão dos demais arquivos?

2019-04-06 16:42 UTC, raianyrufino commented on who/raianyrufino.js
> +});
Pronto

2019-04-07 14:21 UTC, dfquaresma approved these changes

2019-04-27 14:57 UTC, merged