Add amintasvrp.js
Guardians-DSC/iarl-who pull request #15
Opened 2019-04-06 14:09 UTC by amintasvrp

The file _amintasvrp.js_ has been added to be able to contribute with the others **IARL** repositories

2019-04-06 16:07 UTC, dfquaresma requested changes
Olá @amintasvrp. Obrigado por demonstrar o interesse em fazer parte do time. Poderia adicionar sua modificação na descrição da PR?

2019-04-06 16:08 UTC, dfquaresma requested changes
Além disso, poderia dar uma conferida nas sugestões abaixo? Valeu!

2019-04-06 16:08 UTC, dfquaresma commented on who/amintasvrp.js
> +
```suggestion

```

2019-04-06 16:08 UTC, dfquaresma commented on who/amintasvrp.js
> +
Poderia remover esse espaço em branco para manter o padrão dos demais arquivos?

2019-04-06 18:16 UTC, dfquaresma requested changes
Faltou também atualizar o index.html

2019-04-06 18:27 UTC, amintasvrp commented
Minha motivação para fazer parte do IARL é unir o útil ao agradável ao contribuir com uma ferramenta que auxiliará os alunos da graduação, ao mesmo tempo em que troco conhecimentos de forma a agregar a mim e aos demais.

2019-04-06 18:38 UTC, amintasvrp commented on who/amintasvrp.js
> +
Acabei de remover

2019-04-07 14:19 UTC, dfquaresma requested changes

2019-04-07 14:19 UTC, dfquaresma commented on who/amintasvrp.js
> +  });
```suggestion
  });
  
```

2019-04-07 14:20 UTC, dfquaresma commented on who/amintasvrp.js
> +  });
Desculpa. Na minha última sugestão não fui muito preciso. Poderia fazer esta última modificação?

2019-04-07 14:24 UTC, dfquaresma approved these changes

2019-04-24 01:25 UTC, merged